### PR TITLE
refactor:  make project more Zig-idiomatic

### PR DESCRIPTION
**Pull request by tensorush**
Hi @ATTron, great work on this library! It's cool to see more astro-/space-related Zig projects, especially since it's kind of been a Zig theme for some time, with the [first Zig mascot, Zero, jet-packing around in a spacesuit](https://github.com/ziglang/logo/blob/master/zero.svg).

I decided to contribute some changes to make your project have a more cleaned-up, Zig-idiomatic style.

See the official [Zig Style Guide](https://ziglang.org/documentation/0.13.0/#Style-Guide) to explain some of the code changes. As for the removal of `const Self = @This();` in most places, see [this post from Loris](https://zig.news/kristoff/dont-self-simple-structs-fj8).

Also, I have a [project](https://github.com/tensorush/liza) that generates a new Zig executable or library project with the common repo niceties included, some of which I've added in this PR. For instance, now you can run all the build steps at once with `zig build`. I wanted to add a step to run all the examples from the README as well, but I guess this PR is large enough, so I can do it for you in the next one.

Feel free to point out anything that you think should be done differently. Cheers!

### CODE REVIEW

**Comment by ATTron** [comment]
hey @tensorush! thanks for doing all this cleanup! Appreciate the help :1st_place_medal:

**Comment by ATTron** [comment]
im happy with these. Thanks!

**Comment by tensorush** [comment]
Awesome! You might have to switch GitHub Pages deployment from "Deploying from a branch" (by default) to "GitHub Actions".
Screenshot

**Comment by ATTron** [comment]
yup, just made that change and updated it. It looks like the docs deployed but the landing page is for Datetime only ? Is that expected or should the entire lib be showing in the root ? The entire lib is there, just have to search for it

**Comment by tensorush** [comment]
Yeah, must be a bug. Everything that is `pub` and has doc comments has be there. Maybe we should update the CI/CD to run on Zig master, since at 0.13.0 the new doc just got added, so it had more bugs. I can update those to master with the next PR if it's ok

**Comment by ATTron** [comment]
no worries, i can bump to master, and see how things look

**Comment by ATTron** [comment]
hmm yeah looks like that doesnt fix it. Oh well, no big deal for now, just whenever you have your next PR see if you can find a solution. Thanks!

**Pull request merged**
